import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from '@/components/Layouts/Header'; // Adjust the path based on your file structure
//import { AuthProvider } from "@/context/AuthContext"; // Import AuthProvider
//import { ChangeDateProvider } from "@/context/ChangeDateContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {/* Wrap the application with AuthProvider */}
          <Header />
          <main>{children}</main>
      </body>
    </html>
  );
}
